In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
train_df = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/ratings_train.txt", sep="\t")
train_df.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [12]:
!pwd

/mnt/c/Fintech_service/06machine learning


In [13]:
test_df = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/ratings_train.txt", sep="\t")
test_df.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [14]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  149995 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [15]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        150000 non-null  int64 
 1   document  149995 non-null  object
 2   label     150000 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 3.4+ MB


In [16]:
train_df.dropna(inplace=True)
test_df.dropna(inplace=True)

In [17]:
print(train_df.info())
print(test_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        149995 non-null  int64 
 1   document  149995 non-null  object
 2   label     149995 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 4.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 149995 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        149995 non-null  int64 
 1   document  149995 non-null  object
 2   label     149995 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 4.6+ MB
None


In [18]:
train_df['document']

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 149995, dtype: object

In [19]:
import string

In [20]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

# 정규표현식 re
* import re
* pattern = r'[가-힣0-9a-zA-Z]+'  한글, 숫자, 영어 대소문자만 추출
* matches = re.findall(pattern, data)

In [21]:
import re

In [22]:
def text_clean(x):
    pattern = r'[가-힣0-9a-zA-Z]+'
    matches = re.findall(pattern, x)
    matches = " ".join(matches)
    return matches

In [23]:
train_df['document'] = train_df['document'].apply(text_clean)

In [24]:
test_df['document'] = test_df['document'].apply(text_clean)

In [25]:
test_df['document']

0                                         아 더빙 진짜 짜증나네요 목소리
1                              흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                                교도소 이야기구먼 솔직히 재미는 없다 평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                      인간이 문제지 소는 뭔죄인가
149996                                           평점이 너무 낮아서
149997                        이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다
149998                          청춘 영화의 최고봉 방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 149995, dtype: object

In [31]:
train_X = train_df['document']
test_X = test_df['document']

In [32]:
train_y =  train_df['label']
test_y = test_df['label']

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv = CountVectorizer()
train_X_cv = cv.fit_transform(train_X)
test_X_cv = cv.transform(test_X)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv, train_y, test_size=0.4, random_state=7)

In [37]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [38]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
pred = mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8213773792459749
              precision    recall  f1-score   support

           0       0.85      0.78      0.82     30158
           1       0.80      0.86      0.83     29840

    accuracy                           0.82     59998
   macro avg       0.82      0.82      0.82     59998
weighted avg       0.82      0.82      0.82     59998



In [39]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8968165605520184
              precision    recall  f1-score   support

           0       0.91      0.88      0.90     75170
           1       0.88      0.91      0.90     74825

    accuracy                           0.90    149995
   macro avg       0.90      0.90      0.90    149995
weighted avg       0.90      0.90      0.90    149995



# Konlpy의 Mecab을 이용해 형태소 분리

In [40]:
from konlpy.tag import Mecab
mecab = Mecab()

In [41]:
def tokenizer(text):
    tokens = mecab.morphs(text)
    return tokens

## CounterVectorizer, TfidVectorizer

### 1. tokenizer:
설명: 텍스트 데이터를 단어(token) 단위로 나누는 역할을 합니다. tokenizer=tokenizer는 사용자가 정의한 tokenizer 함수를 사용한다는 의미입니다.<br>
예시: 이 tokenizer가 형태소 분석기일 수 있으며, 한국어 데이터를 처리할 때 주로 사용됩니다. 형태소 분석기를 사용하면 문장을 형태소 단위로 분리하여 보다 세밀한 단어 처리 및 분석을 할 수 있습니다.<br>
기본값: None일 경우, 기본적으로 CountVectorizer는 공백이나 기호를 기준으로 텍스트를 나누고, token_pattern='\b\w+\b'을 사용해 단어를 추출합니다.<br>
### 2. ngram_range=(1,2):
설명: ngram_range는 벡터화할 때 단어 단위의 범위를 지정합니다. (1,2)로 설정된 경우, 1-gram과 2-gram을 모두 포함합니다. 즉, 단일 단어와 단어 2개의 조합(예: "좋다", "영화 좋다")을 모두 벡터화에 포함합니다.<br>
n-gram의 장점: 단어 간의 관계를 더 잘 반영할 수 있습니다. 예를 들어, "좋다"와 "영화 좋다"는 서로 다른 맥락에서 사용될 수 있으므로, 이를 별도로 처리할 수 있습니다.<br>
예시: "이 영화는 정말 좋다"라는 문장이 있을 경우, ngram_range=(1,2)를 적용하면 다음과 같은 n-gram이 생성됩니다:<br>
1-gram: ['이', '영화는', '정말', '좋다']<br>
2-gram: ['이 영화는', '영화는 정말', '정말 좋다']<br>
### 3. min_df=3:
설명: min_df는 단어가 등장하는 최소 문서 수를 설정하는 하이퍼파라미터입니다. min_df=3은 단어가 최소 3개 이상의 문서에 등장해야 해당 단어를 벡터화 과정에 포함시키는 것을 의미합니다.<br>
목적: 너무 드물게 등장하는 단어는 의미가 없거나, 오히려 성능을 저해할 수 있기 때문에 이를 제거하기 위해 사용합니다. 일반적으로 자주 등장하지 않는 단어는 데이터에 노이즈를 추가하는 경향이 있습니다.<br>
예시: "사자성어" 같은 단어가 데이터셋 내에서 단 1~2회만 등장한다면, min_df=3으로 설정된 경우 이 단어는 벡터화에 포함되지 않습니다.<br>
### 4. max_df=0.9:
설명: max_df는 단어가 등장하는 문서 비율의 최대치를 설정하는 하이퍼파라미터입니다.<br> max_df=0.9는 단어가 전체 문서의 90% 이하에서 등장할 때만 벡터화에 포함시킵니다. 즉, 너무 자주 등장하는 단어(예: 불용어)는 제외됩니다.<br>
목적: 모든 문서에서 지나치게 자주 등장하는 단어(예: "이", "그리고" 등)는 의미를 거의 제공하지 않기 때문에 이를 제거하기 위해 사용됩니다. 이처럼 너무 빈번하게 등장하는 단어는 일반적으로 텍스트의 구분에 유용하지 않다고 여겨집니다.<br>
예시: 만약 "영화"라는 단어가 거의 모든 문서에서 등장한다면, max_df=0.9로 설정된 경우 이 단어는 벡터화 과정에서 제외됩니다.

In [42]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [43]:
c_vec = CountVectorizer(tokenizer=tokenizer, ngram_range=(1,2), min_df=3, max_df=0.9)
train_X_cv = c_vec.fit_transform(train_X)
test_X_cv = c_vec.transform(test_X)

/home/user/miniforge3/envs/nlp/lib/python3.10/site-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv, train_y, test_size=0.4, random_state=7)

In [51]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [52]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
pred = mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8581952731757725
              precision    recall  f1-score   support

           0       0.86      0.86      0.86     30158
           1       0.86      0.85      0.86     29840

    accuracy                           0.86     59998
   macro avg       0.86      0.86      0.86     59998
weighted avg       0.86      0.86      0.86     59998



In [53]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8840361345378179
              precision    recall  f1-score   support

           0       0.88      0.89      0.88     75170
           1       0.89      0.88      0.88     74825

    accuracy                           0.88    149995
   macro avg       0.88      0.88      0.88    149995
weighted avg       0.88      0.88      0.88    149995



## 1. CountVectorizer와 TfidfVectorizer의 차이점
### 1) CountVectorizer: 단어 빈도(횟수) 기반 벡터화
작동 방식: CountVectorizer는 각 문서에서 등장한 단어의 **횟수(빈도)**를 기준으로 벡터를 만듭니다. 단순히 각 문서에서 특정 단어가 몇 번 등장했는지를 세어 벡터화합니다.<br>
특징:
각 단어의 빈도가 높을수록 해당 단어의 중요성이 더 크다고 가정합니다.<br>
빈도가 높다는 것만을 고려하기 때문에, 모든 문서에서 자주 등장하는 단어도 중요한 단어로 처리될 수 있습니다.<br>
예시:<br>
예를 들어, 두 개의 문서가 있다면:<br>
문서 1: "고양이가 나무 위에 있다."<br>
문서 2: "나무 아래에 고양이가 있다."<br>
이 두 문서를 CountVectorizer로 변환하면 단어 빈도가 포함된 벡터가 생성됩니다:<br>
['고양이': 2, '나무': 2, '위에': 1, '아래에': 1, '있다': 2]<br>
### 2) TfidfVectorizer: TF-IDF (Term Frequency-Inverse Document Frequency) 기반 벡터화
작동 방식: TfidfVectorizer는 단어의 빈도뿐만 아니라, 단어의 중요도를 계산합니다. 여기서는 TF-IDF 값을 사용하여 문서 간 차별성을 강조합니다.<br>
TF (Term Frequency): 단어가 문서에서 얼마나 자주 등장했는지를 나타냅니다.<br>
IDF (Inverse Document Frequency): 단어가 다른 문서에 얼마나 자주 등장하지 않았는지를 나타냅니다. 자주 등장하지 않는 단어는 더 중요한 단어로 간주합니다.<br>
특징:<br>
TF-IDF는 문서 전체에서 자주 등장하는 흔한 단어들(예: "그리고", "이다" 등)의 중요도를 낮추고, 문서에서만 중요한 단어들의 중요도를 높입니다.<br>
단순히 빈도가 높은 단어보다 특정 문서에서 더 특징적인 단어에 더 높은 가중치를 부여합니다.<br>
예시:<br>
위의 문서 1과 문서 2에 대해 TfidfVectorizer로 변환하면, 공통 단어들(예: "있다", "고양이")의 중요도는 낮아지고, 차별적인 단어(예: "위에", "아래에")의 중요도는 상대적으로 높아집니다.

In [54]:
# 1) CountVectorizer 사용법
from sklearn.feature_extraction.text import CountVectorizer

# 예시 문서
documents = ["고양이가 나무 위에 있다.", "나무 아래에 고양이가 있다."]

# CountVectorizer 초기화 및 문서 벡터화
c_vec = CountVectorizer()

# 문서에 대해 fit_transform 적용 (단어의 빈도를 세서 벡터화)
X = c_vec.fit_transform(documents)

# 벡터 결과 출력 (단어별 빈도 확인)
print(c_vec.get_feature_names_out())  # 벡터화된 단어 목록
print(X.toarray())  # 단어 빈도 벡터

['고양이가' '나무' '아래에' '위에' '있다']
[[1 1 0 1 1]
 [1 1 1 0 1]]


In [55]:
# 2) TfidfVectorizer 사용법
from sklearn.feature_extraction.text import TfidfVectorizer

# 예시 문서
documents = ["고양이가 나무 위에 있다.", "나무 아래에 고양이가 있다."]

# TfidfVectorizer 초기화 및 문서 벡터화
tfidf_vec = TfidfVectorizer()

# 문서에 대해 fit_transform 적용 (TF-IDF로 벡터화)
X = tfidf_vec.fit_transform(documents)

# 벡터 결과 출력 (단어별 TF-IDF 가중치 확인)
print(tfidf_vec.get_feature_names_out())  # 벡터화된 단어 목록
print(X.toarray())  # TF-IDF 값으로 변환된 벡터


['고양이가' '나무' '아래에' '위에' '있다']
[[0.44832087 0.44832087 0.         0.63009934 0.44832087]
 [0.44832087 0.44832087 0.63009934 0.         0.44832087]]


### CountVectorizer와 TfidfVectorizer 비교

| **특성**             | **CountVectorizer**                                     | **TfidfVectorizer**                                               |
|----------------------|--------------------------------------------------------|-------------------------------------------------------------------|
| **기반**             | 단어의 단순 빈도                                        | 단어 빈도 + 문서 내에서의 상대적 중요도(TF-IDF)                     |
| **단어 빈도 계산**    | 문서에서 등장한 단어의 단순한 등장 횟수를 셈            | 단어의 등장 횟수(TF)와 해당 단어가 문서들에서 얼마나 자주 등장하지 않았는지를 함께 고려(IDF) |
| **빈번한 단어 처리**  | 문서에서 자주 등장하는 단어일수록 높은 가중치를 부여    | 문서에서 흔한 단어는 가중치를 낮추고, 드문 단어는 높은 가중치를 부여   |
| **주요 용도**        | 단순한 단어 빈도 기반 분석이 필요할 때 사용             | 문서 간 차별적인 단어를 구별할 때 유용                                |
| **계산 비용**         | 상대적으로 적음                                         | 상대적으로 더 복잡하고 계산 비용이 높음                                |


In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [57]:
tfid_vec = TfidfVectorizer(tokenizer=tokenizer, ngram_range=(1,2), min_df=4, max_df=0.9)
train_X_cv = tfid_vec.fit_transform(train_X)
test_X_cv = tfid_vec.transform(test_X)

/home/user/miniforge3/envs/nlp/lib/python3.10/site-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(train_X_cv, train_y, test_size=0.4, random_state=7)

In [60]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [61]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
pred = mnb.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8607953598453282
              precision    recall  f1-score   support

           0       0.86      0.87      0.86     30158
           1       0.87      0.85      0.86     29840

    accuracy                           0.86     59998
   macro avg       0.86      0.86      0.86     59998
weighted avg       0.86      0.86      0.86     59998



In [62]:
test_pred = mnb.predict(test_X_cv)
print(accuracy_score(test_y, test_pred))
print(classification_report(test_y , test_pred))

0.8847761592053068
              precision    recall  f1-score   support

           0       0.88      0.89      0.89     75170
           1       0.89      0.88      0.88     74825

    accuracy                           0.88    149995
   macro avg       0.88      0.88      0.88    149995
weighted avg       0.88      0.88      0.88    149995



In [64]:
# !pip install xgboost
# !pip install lightgbm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 33.3 MB/s eta 0:00:00


# 1. XGBoost로 분석하는 코드

In [65]:
# 필요한 라이브러리 import
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report

# XGBoost 모델 생성 및 학습
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train)

# 테스트 데이터로 예측
xgb_pred = xgb_model.predict(X_test)

# 성능 평가
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))

# 실제 테스트 데이터에 대해 예측 및 평가
xgb_test_pred = xgb_model.predict(test_X_cv)
print("XGBoost Test Data Accuracy:", accuracy_score(test_y, xgb_test_pred))
print(classification_report(test_y, xgb_test_pred))

/home/user/miniforge3/envs/nlp/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [15:24:42] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBoost Accuracy: 0.8113437114570485
              precision    recall  f1-score   support

           0       0.79      0.86      0.82     30158
           1       0.84      0.77      0.80     29840

    accuracy                           0.81     59998
   macro avg       0.81      0.81      0.81     59998
weighted avg       0.81      0.81      0.81     59998

XGBoost Test Data Accuracy: 0.8272275742524751
              precision    recall  f1-score   support

           0       0.80      0.87      0.83     75170
           1       0.86      0.78      0.82     74825

    accuracy                           0.83    149995
   macro avg       0.83      0.83      0.83    149995
weighted avg       0.83      0.83      0.83    149995



# 2. LightGBM으로 분석하는 코드

In [66]:
# 필요한 라이브러리 import
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report

# LightGBM 모델 생성 및 학습
lgb_model = LGBMClassifier(verbose=-1)
lgb_model.fit(X_train, y_train)

# 테스트 데이터로 예측
lgb_pred = lgb_model.predict(X_test)

# 성능 평가
print("LightGBM Accuracy:", accuracy_score(y_test, lgb_pred))
print(classification_report(y_test, lgb_pred))

# 실제 테스트 데이터에 대해 예측 및 평가
lgb_test_pred = lgb_model.predict(test_X_cv)
print("LightGBM Test Data Accuracy:", accuracy_score(test_y, lgb_test_pred))
print(classification_report(test_y, lgb_test_pred))

LightGBM Accuracy: 0.8144271475715857
              precision    recall  f1-score   support

           0       0.80      0.84      0.82     30158
           1       0.83      0.78      0.81     29840

    accuracy                           0.81     59998
   macro avg       0.82      0.81      0.81     59998
weighted avg       0.82      0.81      0.81     59998

LightGBM Test Data Accuracy: 0.8227607586919564
              precision    recall  f1-score   support

           0       0.81      0.85      0.83     75170
           1       0.84      0.79      0.82     74825

    accuracy                           0.82    149995
   macro avg       0.82      0.82      0.82    149995
weighted avg       0.82      0.82      0.82    149995

