In [1]:
import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import os
# import warnings
# warnings.filterwarnings("ignore")
# import chart_studio.plotly as py
# from plotly.offline import init_notebook_mode, iplot
# init_notebook_mode(connected=True)
# import plotly.graph_objs as go
# import koreanize_matplotlib

# 카드소비데이터

In [73]:
card_data = pd.read_json("./data/카드소비데이터.json")
card_data.head(10)

TA_YMD  CTY_RGN_NO  ADMI_CTY_NO CARD_TPBUZ_CD CARD_TPBUZ_NM_1  \
0  20240101       41650     41650520           F09           생활서비스   
1  20240101       41650     41650520           F09           생활서비스   
2  20240101       41650     41650520           F09           생활서비스   
3  20240101       41650     41650520           F09           생활서비스   
4  20240101       41650     41650520           F09           생활서비스   
5  20240101       41650     41650520           F09           생활서비스   
6  20240101       41650     41650520           F09           생활서비스   
7  20240101       41650     41650520           F09           생활서비스   
8  20240101       41650     41650520           F09           생활서비스   
9  20240101       41650     41650520           F09           생활서비스   

  CARD_TPBUZ_NM_2  HOUR SEX  AGE  DAY     AMT  CNT  
0            연료판매     7   M    4    1  273974    7  
1            연료판매     7   M    5    1  228624    5  
2            연료판매     7   M    7    1  392890    7  
3            연료판매     8   F    3    1  114312    5  
4            연료판매     8   F    5    1  406951   10  
5            연료판매     8   F    6    1  109740    3  
6            연료판매     8   M    4    1  194331    5  
7            연료판매     8   M    5    1  201715    3  
8            연료판매     8   M    6    1  139145    5  
9            연료판매     8   M    7    1  114312    3

In [28]:
print(len(card_data.columns))

12


In [30]:
card_new_columns = ['기준년월일', '시군구코드', '행정동코드', '카드사_업종분류코드', '카드사_업종대분류명', '카드사_업종중분류명', '시간대', '성별', '연령별', '요일', '매출금액', '매출건수']

In [31]:
print(len(card_new_columns))

12


In [32]:
card_data.columns = card_new_columns

In [33]:
card_data.head()

기준년월일  시군구코드     행정동코드 카드사_업종분류코드 카드사_업종대분류명 카드사_업종중분류명  시간대 성별  연령별  \
0  20240101  41650  41650520        F09      생활서비스       연료판매    7  M    4   
1  20240101  41650  41650520        F09      생활서비스       연료판매    7  M    5   
2  20240101  41650  41650520        F09      생활서비스       연료판매    7  M    7   
3  20240101  41650  41650520        F09      생활서비스       연료판매    8  F    3   
4  20240101  41650  41650520        F09      생활서비스       연료판매    8  F    5   

   요일    매출금액  매출건수  
0   1  273974     7  
1   1  228624     5  
2   1  392890     7  
3   1  114312     5  
4   1  406951    10

In [34]:
card_data['카드사_업종분류코드'].unique()

array(['F09', 'O03', 'O04', 'Q01', 'Q02', 'Q03', 'Q04', 'Q05', 'Q06',
       'Q07', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'R02', 'S01',
       'S02', 'S06', 'Y03', 'R05', 'S03', 'S05', 'U04', 'D01', 'D02',
       'D05', 'D06', 'D08', 'D09', 'D10', 'D11', 'D12', 'D15', 'D16',
       'D19', 'F02', 'F06', 'F07', 'F01', 'F05', 'F10', 'F14', 'F15',
       'O01', 'Q08', 'T04', 'Y04', 'Y05', 'D04', 'F12', 'O02', 'T02',
       'D14', 'U01', 'U02', 'D03', 'R06', 'Y01', 'F11', 'Q09', 'Q16',
       'R03', 'R04', 'R07', 'T01'], dtype=object)

In [35]:
card_data['카드사_업종대분류명'].unique()

array(['생활서비스', '여가/오락', '음식', '학문/교육', '의료/건강', '공공/기업/단체', '미디어/통신',
       '소매/유통', '공연/전시'], dtype=object)

In [36]:
card_data['카드사_업종중분류명'].unique()

array(['연료판매', '일반스포츠', '취미/오락', '간이주점', '고기요리', '닭/오리요리', '별식/퓨전요리',
       '부페', '분식', '양식', '일식/수산물', '제과/제빵/떡/케익', '중식', '커피/음료', '패스트푸드',
       '한식', '독서실/고시원', '수의업', '의약/의료품', '기타의료', '기업', '외국어학원', '일반병원',
       '종합병원', '기타결제', '가전제품', '건강/기호식품', '선물/완구', '스포츠/레져용품', '음/식료품소매',
       '의복/의류', '인테리어/가정용품', '종합소매점', '차량관리/부품', '패션잡화', '화장품소매', '제조/도매',
       '미용서비스', '세탁/가사서비스', '수리서비스', '광고/인쇄/인화', '사우나/휴게시설', '차량관리/서비스',
       '무점포서비스', '금융상품/서비스', '숙박', '유흥주점', '문화서비스', '단체', '종교', '서적/도서',
       '여행/유학대행', '요가/단전/마사지', '공연관람', '악기/공예', '인터넷쇼핑', '방송/미디어',
       '사무/교육용품', '유아교육', '공공기관', '보안/운송', '음식배달서비스', '휴게소/대형업체', '기타교육',
       '예체능계학원', '입시학원', '전시장'], dtype=object)

In [37]:
card_data['시간대'].unique()

array([ 7,  8,  9, 10,  2,  3,  4,  5,  6,  1], dtype=int64)

In [38]:
card_data['매출금액'].unique()

array([273974, 228624, 392890, ..., 473390, 344538, 557423], dtype=int64)

In [39]:
card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10825 entries, 0 to 10824
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   기준년월일       10825 non-null  int64 
 1   시군구코드       10825 non-null  int64 
 2   행정동코드       10825 non-null  int64 
 3   카드사_업종분류코드  10825 non-null  object
 4   카드사_업종대분류명  10825 non-null  object
 5   카드사_업종중분류명  10825 non-null  object
 6   시간대         10825 non-null  int64 
 7   성별          10825 non-null  object
 8   연령별         10825 non-null  int64 
 9   요일          10825 non-null  int64 
 10  매출금액        10825 non-null  int64 
 11  매출건수        10825 non-null  int64 
dtypes: int64(8), object(4)
memory usage: 1015.0+ KB


# 분석시스템_경기도_카드매출_시간대별_집계

In [6]:
card_system_data = pd.read_json("./data/분석시스템_경기도_카드매출_시간대별_집계.json")
card_system_data.tail(3)

STD_YM  SIGN_CD TMZON_CD     SALES_AMT  SALES_AMT_RATE
2043  202101     4183     TZ01     840775652            1.08
2044  202101     4111     TZ02   22421445505            2.16
2045  202101     4113     TZ02  153998050461            3.33

In [7]:
card_system_data['TMZON_CD'].unique()

array(['TZ10', 'TZ08', 'TZ09', 'TZ06', 'TZ07', 'TZ04', 'TZ05', 'TZ02',
       'TZ03', 'TOT', 'TZ01'], dtype=object)

In [40]:
card_system_data_new_colmuns = ['기준년월', '시군코드', '시간대코드', '매출금액', '매출금액비율']

In [41]:
card_system_data.columns = card_system_data_new_colmuns

In [42]:
card_system_data.head(5)

기준년월  시군코드 시간대코드        매출금액  매출금액비율
0  202106  4129  TZ10   212710509    0.28
1  202106  4131  TZ10  1134667990    0.64
2  202106  4136  TZ10  2661106579    0.54
3  202106  4137  TZ10  1462028549    0.81
4  202106  4139  TZ10  3309249288    0.68

# 신용보증기금_업종별 부실률 정보_20210923(1)

In [61]:
insolvency_rate_data = pd.read_csv("./data/신용보증기금_업종별 부실률 정보_20210923(1).csv", encoding='euc-kr')
insolvency_rate_data.tail(3)

업종코드  업종차수  업종보증기업수      업종보증잔액  업종부실기업수     업종부실잔액 삭제여부  최종수정수
997  A01123    10       18  6439599400        0          0    N      1
998  A01122    10        7   855690000        0          0    N      1
999  A01121    10        8  2303850000        1  441000000    N      1

In [62]:
insolvency_rate_data['업종코드'].unique()

array(['A01110', 'Q87299', 'Q87294', 'Q87293', 'Q87292', 'Q87291',
       'Q87210', 'Q87139', 'Q87131', 'Q87112', 'Q87111', 'Q86909',
       'Q86902', 'Q86901', 'Q86300', 'Q86204', 'Q86203', 'Q86202',
       'Q86201', 'Q86105', 'Q86104', 'Q86103', 'Q86102', 'Q86101',
       'P85709', 'P85701', 'P85699', 'P85691', 'P85669', 'P85661',
       'P85650', 'P85640', 'P85632', 'P85631', 'P85629', 'P85622',
       'P85621', 'P85614', 'P85613', 'P85612', 'P85611', 'P85503',
       'P85502', 'P85501', 'P85430', 'P85410', 'P85110', 'N76390',
       'N76320', 'N76310', 'N76299', 'N76292', 'N76291', 'N76220',
       'N76210', 'N76190', 'N76110', 'N75999', 'N75994', 'N75993',
       'N75992', 'N75991', 'N75919', 'N75912', 'N75911', 'N75320',
       'N75310', 'N75290', 'N75210', 'N75122', 'N75121', 'N75110',
       'N74300', 'N74220', 'N74212', 'N74211', 'N74100', 'M73909',
       'M73904', 'M73903', 'M73902', 'M73901', 'M73303', 'M73302',
       'M73301', 'M73209', 'M73203', 'M73202', 'M73201', 'M731

In [63]:
insolvency_rate_data['업종차수'].unique()

array([10], dtype=int64)

# 한국 표준 산업 체계

In [64]:
# 엑셀 파일 불러오기
file_path = './data/한국표준산업분류체계.xlsx'
classification_data = pd.read_excel(file_path)

# 필요한 열만 추출 (코드1, 코드5, 항목명5)
selected_columns = classification_data[['코드1', '코드5', '항목명5']].dropna()

# 결과 확인
print(selected_columns.head(10))

  코드1   코드5                  항목명5
0   A  1110      곡물 및 기타 식량작물 재배업
1   A  1121              채소작물 재배업
2   A  1122              화훼작물 재배업
3   A  1123           종자 및 묘목 생산업
4   A  1131              과실작물 재배업
5   A  1132      음료용 및 향신용 작물 재배업
6   A  1140             기타 작물 재배업
7   A  1151               콩나물 재배업
8   A  1152  채소, 화훼 및 과실작물 시설 재배업
9   A  1159           기타 시설작물 재배업


In [65]:
import pandas as pd

# '코드1'과 '코드5'를 키로, '항목명5'를 값으로 하는 딕셔너리 생성
classification_data['키'] = classification_data['코드1'].astype(str) + classification_data['코드5'].astype(str)
code_to_name = dict(zip(classification_data['키'], classification_data['항목명5']))

# insolvency_rate_data에서도 '업종코드'와 '코드5'를 연결하여 키 생성
insolvency_rate_data['키'] = insolvency_rate_data['업종코드']

# '키' 값을 이용해 '항목명5'로 대체
insolvency_rate_data['업종코드'] = insolvency_rate_data['키'].map(code_to_name)

# 결과 확인
print(insolvency_rate_data[['업종코드']].head(10))


                   업종코드
0                   NaN
1    그 외 기타 비거주 복지 서비스업
2       사회복지 상담 서비스 제공업
3          방문 복지서비스 제공업
4             종합복지관 운영업
5            직업 재활원 운영업
6              보육시설 운영업
7    그 외 기타 거주 복지시설 운영업
8  아동 및 부녀자 거주 복지시설 운영업
9        노인 양로 복지시설 운영업


In [69]:
insolvency_rate_new_data = insolvency_rate_data.copy()
insolvency_rate_new_data.head(10)

업종코드  업종차수  업종보증기업수      업종보증잔액  업종부실기업수    업종부실잔액 삭제여부  \
0                   NaN    10        5   282250000        1  76500000    N   
1    그 외 기타 비거주 복지 서비스업    10       31  2163805000        1  42300000    N   
2       사회복지 상담 서비스 제공업    10       15  1665500000        0         0    N   
3          방문 복지서비스 제공업    10       27  2363357540        0         0    N   
4             종합복지관 운영업    10        8   714533348        0         0    N   
5            직업 재활원 운영업    10        1    27000000        0         0    N   
6              보육시설 운영업    10        3    65650000        0         0    N   
7    그 외 기타 거주 복지시설 운영업    10        2    65000000        0         0    N   
8  아동 및 부녀자 거주 복지시설 운영업    10        1    40000000        0         0    N   
9        노인 양로 복지시설 운영업    10        8  1682573000        0         0    N   

   최종수정수       키  
0      1  A01110  
1      1  Q87299  
2      1  Q87294  
3      1  Q87293  
4      1  Q87292  
5      1  Q87291  
6      1  Q87210  
7      1  Q87139  
8      1  Q87131  
9      1  Q87112

In [70]:
insolvency_rate_new_data['업종코드'].unique()

array([nan, '그 외 기타 비거주 복지 서비스업', '사회복지 상담 서비스 제공업', '방문 복지서비스 제공업',
       '종합복지관 운영업', '직업 재활원 운영업', '보육시설 운영업', '그 외 기타 거주 복지시설 운영업',
       '아동 및 부녀자 거주 복지시설 운영업', '노인 양로 복지시설 운영업', '노인 요양 복지시설 운영업',
       '그 외 기타 보건업', '유사 의료업', '앰뷸런스 서비스업', '공중 보건 의료업',
       '방사선 진단 및 병리 검사 의원', '한의원', '치과의원', '일반의원', '요양병원', '한방병원', '치과병원',
       '일반병원', '종합병원', '기타 교육지원 서비스업', '교육관련 자문 및 평가업',
       '그 외 기타 분류 안된 교육기관', '컴퓨터 학원', '기타 기술 및 직업 훈련학원', '운전학원',
       '직원 훈련기관', '사회교육시설', '기타 교습학원', '외국어학원', '기타 예술학원', '미술학원', '음악학원',
       '청소년 수련시설 운영업', '레크리에이션 교육기관', '기타 스포츠 교육기관', '태권도 및 무술 교육기관',
       '온라인 교육학원', '방문 교육학원', '일반 교과학원', '대안학교', '특수학교', '유아 교육기관',
       '기타 산업용 기계 및 장비 임대업', '컴퓨터 및 사무용 기계ㆍ장비 임대업',
       '건설 및 토목공사용 기계ㆍ장비 임대업', '그 외 기타 개인 및 가정용품 임대업', '의류 임대업', '서적 임대업',
       '음반 및 비디오물 임대업', '스포츠 및 레크리에이션 용품 임대업', '기타 운송장비 임대업', '자동차 임대업',
       '그 외 기타 분류 안된 사업 지원 서비스업', '포장 및 충전업', '신용 조사 및 추심 대행업',
       '전시, 컨벤션 및 행사 대행업', '콜센터 및 텔레마케팅 서비스업', '기타 사무 지원 서비스업', '복

In [71]:
insolvency_rate_new_data

업종코드  업종차수  업종보증기업수      업종보증잔액  업종부실기업수     업종부실잔액 삭제여부  \
0                   NaN    10        5   282250000        1   76500000    N   
1    그 외 기타 비거주 복지 서비스업    10       31  2163805000        1   42300000    N   
2       사회복지 상담 서비스 제공업    10       15  1665500000        0          0    N   
3          방문 복지서비스 제공업    10       27  2363357540        0          0    N   
4             종합복지관 운영업    10        8   714533348        0          0    N   
..                  ...   ...      ...         ...      ...        ...  ...   
995                 NaN    10        8   761300000        0          0    N   
996                 NaN    10        3  1157750000        0          0    N   
997                 NaN    10       18  6439599400        0          0    N   
998                 NaN    10        7   855690000        0          0    N   
999                 NaN    10        8  2303850000        1  441000000    N   

     최종수정수       키  
0        1  A01110  
1        1  Q87299  
2        1  Q87294  
3        1  Q87293  
4        1  Q87292  
..     ...     ...  
995      1  A01140  
996      1  A01131  
997      1  A01123  
998      1  A01122  
999      1  A01121  

[1000 rows x 9 columns]

# 신용보증기금_업종별 보증해지 현황 요약_20230830.csv

In [11]:
Warranty_termination_data = pd.read_csv("./data/신용보증기금_업종별 보증해지 현황 요약_20230830.csv", encoding='euc-kr')
Warranty_termination_data.head(3)

기준일자    업종코드 일반창업구분  지역  주채무상환해지기업수  기타해지기업수  기타해지해지건수
0  2018-12-07  C20201     전체  전남           1        1         1
1  2018-12-07  C20201     전체  미상           0        6         5
2  2018-12-07  C20201     창업  전체           0        3         2

In [15]:
# guarantee_data = pd.read_csv("./data/신용보증기금_업종별 보증 잔액 규모_20210923.csv", encoding='euc-kr')
# guarantee_data.head(30)

브릿지론구분 통계기업규모 제조건설업종구분 통계직위재구분  취급건수  취급기업수  보증잔액건수  보증잔액기업수
0      일반   중소기업       전체    위탁보증     0      0      76       66
1      전체   중소기업      제조업   직접+위탁     0      0       3        3
2      전체   중소기업      제조업    직접보증     0      0       3        3
3      전체   중소기업       전체   직접+위탁    17      0    3770     2565
4      전체   중소기업       전체    위탁보증     0      0      29       28
5      전체   중소기업       전체    직접보증    17      0    3741     2547
6      전체     전체      제조업   직접+위탁     7      0    1745     1125
7      전체     전체      제조업    위탁보증     0      0      14       13
8      전체     전체      제조업    직접보증     7      0    1731     1115
9      전체     전체       전체   직접+위탁    17      0    3773     2567
10     전체     전체       전체    위탁보증     0      0      29       28
11     전체     전체       전체    직접보증    17      0    3744     2549
12     일반   중소기업      제조업   직접+위탁     0      0       3        2
13     일반   중소기업      제조업    직접보증     0      0       3        2
14     일반   중소기업       전체   직접+위탁    21      2    3985     2639
15     일반   중소기업       전체    위탁보증     0      0      58       58
16     일반   중소기업       전체    직접보증    21      2    3927     2602
17     일반     전체      제조업   직접+위탁    16      2    2573     1643
18     일반     전체      제조업    위탁보증     0      0      38       38
19     일반     전체      제조업    직접보증    16      2    2535     1618
20     일반     전체       전체   직접+위탁    21      2    3985     2639
21     일반     전체       전체    위탁보증     0      0      58       58
22     일반     전체       전체    직접보증    21      2    3927     2602
23     전체   중소기업      제조업   직접+위탁     0      0       3        2
24     전체   중소기업      제조업    직접보증     0      0       3        2
25     전체   중소기업       전체   직접+위탁    21      2    3985     2639
26     전체   중소기업       전체    위탁보증     0      0      58       58
27     전체   중소기업       전체    직접보증    21      2    3927     2602
28     전체     전체      제조업   직접+위탁    16      2    2573     1643
29     전체     전체      제조업    위탁보증     0      0      38       38

In [17]:
# guarantee_data['제조건설업종구분'].unique()

array(['전체', '제조업'], dtype=object)

# 업종별사업체현황

In [43]:
company_data = pd.read_json("./data/업종별사업체현황.json")
company_data.head(30)

EXAMIN_STD_YY SIGUN_NM   ADMZONE_NM              REFINE_LOTNO_ADDR  \
0            2021      가평군   경기도 가평군 상면        경기도 가평군 상면 연하리 179-30번지   
1            2021      가평군  경기도 가평군 가평읍          경기도 가평군 가평읍 복장리 289번지   
2            2021      가평군  경기도 가평군 설악면       경기도 가평군 설악면 사룡리 668-11번지   
3            2021      가평군   경기도 가평군 북면         경기도 가평군 북면 목동리 888-1번지   
4            2021      가평군  경기도 가평군 조종면         경기도 가평군 조종면 현리 296-3번지   
5            2021      가평군  경기도 가평군 청평면  경기도 가평군 청평면 하천리 503-28번지 유성식당   
6            2021      가평군   경기도 가평군 상면        경기도 가평군 상면 덕현리 159-10번지   
7            2021      가평군   경기도 가평군 상면           경기도 가평군 상면 임초리 409번지   
8            2021      가평군   경기도 가평군 북면         경기도 가평군 북면 목동리 924-2번지   
9            2021      가평군  경기도 가평군 청평면        경기도 가평군 청평면 상천리 257-4번지   
10           2021      가평군  경기도 가평군 가평읍          경기도 가평군 가평읍 대곡리 208번지   
11           2021      가평군  경기도 가평군 가평읍        경기도 가평군 가평읍 대곡리 195-3번지   
12           2021      가평군  경기도 가평군 청평면        경기도 가평군 청평면 청평리 354-3번지   
13           2021      가평군  경기도 가평군 조종면        경기도 가평군 조종면 현리 262-60번지   
14           2021      가평군  경기도 가평군 가평읍        경기도 가평군 가평읍 대곡리 270-2번지   
15           2021      가평군  경기도 가평군 조종면        경기도 가평군 조종면 현리 410-44번지   
16           2021      가평군  경기도 가평군 가평읍         경기도 가평군 가평읍 읍내리 74-1번지   
17           2021      가평군  경기도 가평군 조종면          경기도 가평군 조종면 상판리 146번지   
18           2021      가평군   경기도 가평군 북면         경기도 가평군 북면 제령리 544-8번지   
19           2021      가평군  경기도 가평군 조종면       경기도 가평군 조종면 신상리 512-13번지   
20           2021      가평군  경기도 가평군 설악면        경기도 가평군 설악면 회곡리 산70-3번지   
21           2021      가평군  경기도 가평군 조종면        경기도 가평군 조종면 현리 311-10번지   
22           2021      가평군  경기도 가평군 설악면       경기도 가평군 설악면 회곡리 741-10번지   
23           2021      가평군  경기도 가평군 설악면         경기도 가평군 설악면 사룡리 9-37번지   
24           2021      가평군  경기도 가평군 가평읍        경기도 가평군 가평읍 승안리 402-3번지   
25           2021      가평군   경기도 가평군 북면        경기도 가평군 북면 백둔리 417-27번지   
26           2021      가평군  경기도 가평군 청평면        경기도 가평군 청평면 대성리 578-3번지   
27           2021      가평군   경기도 가평군 북면         경기도 가평군 북면 백둔리 709-5번지   
28           2021      가평군   경기도 가평군 북면         경기도 가평군 북면 백둔리 393-1번지   
29           2021      가평군  경기도 가평군 가평읍       경기도 가평군 가평읍 경반리 583-34번지   

                 REFINE_ROADNM_ADDR REFINE_ZIPNO REFINE_WGS84_LAT  \
0              경기도 가평군 상면 기와집길  8-         12444    37.8057076839   
1           경기도 가평군 가평읍 상지로  1074-         12430    37.7371598805   
2         경기도 가평군 설악면 용문천길  153-27         12460    37.6911351872   
3              경기도 가평군 북면 화악산로  8-         12403    37.8860743397   
4              경기도 가평군  청군로  1285-         12438    37.8188907093   
5            경기도 가평군  청군로  10- 유성식당        12450    37.7476112233   
6             경기도 가평군 상면 청군로  316-         12446    37.7568955992   
7           경기도 가평군 상면 청군로  690-13         12447    37.7741902623   
8            경기도 가평군 북면 가화로  1023-         12403    37.8869130763   
9              경기도 가평군  경춘로  1444-         12449    37.7782731509   
10              경기도 가평군  가화로  26-9         12421    37.8223337510   
11               경기도 가평군  가화로  43-         12420    37.8236949593   
12              경기도 가평군  은고개로  44-         12452    37.7382981004   
13           경기도 가평군  현창로44번길  16-         12437    37.8199760774   
14            경기도 가평군 가평읍 광장로  19-         12416    37.8259488552   
15            경기도 가평군 조종면 현창로  26-         12438    37.8171729449   
16        경기도 가평군 가평읍 물안산길  42-107         12411    37.8555203068   
17            경기도 가평군  명지산로  475-0         12431    37.9110903217   
18          경기도 가평군 북면 꽃넘이길  87-25         12405    37.8974302245   
19  경기도 가평군 조종면 운악청계로491번길  154-24         12434    37.8502390725   
20          경기도 가평군 설악면 유명로  2258-         12459    37.7036738992   
21         경기도 가평군 조종면 청군로  1317-0         12438    37.8213669512   
22          경기도 가평군 설악면 유명로  2430-         12459    37.7148551446   
23    경기도 가평군 설악면 자잠로282번길  72-235         12460    3

In [14]:
company_data['INDUST_LGCLAS_NM'].unique()

array(['보건업 및 사회복지 서비스업(86~87)', '숙박 및 음식점업(55~56)', '도매 및 소매업(45~47)',
       '건설업(41~42)', '부동산업(68)', '제조업(10~34)',
       '사업시설 관리, 사업 지원 및 임대 서비스업(74~76)',
       '협회 및 단체, 수리 및 기타 개인 서비스업(94~96)', '교육 서비스업(85)',
       '운수 및 창고업(49~52)', '전문, 과학 및 기술 서비스업(70~73)',
       '예술, 스포츠 및 여가관련 서비스업(90~91)', '정보통신업(58~63)',
       '전기, 가스, 증기 및 공기 조절 공급업(35)', '수도, 하수 및 폐기물 처리, 원료 재생업(36~39)',
       '공공 행정, 국방 및 사회보장 행정(84)', '금융 및 보험업(64~66)', '농업, 임업 및 어업(01~03)',
       '광업(05~08)'], dtype=object)